'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '@/lib/utils';

// ─── Data ─────────────────────────────────────────────────────────────────────

interface StickyNote {
  id: string;
  label: string;
  expanded: string;
}

interface StickyGroup {
  header: string;
  notes: StickyNote[];
}

const leftGroups: StickyGroup[] = [
  {
    header: 'Project Knowledge',
    notes: [
      {
        id: 'l1',
        label: 'Next.js 16, TypeScript, Tailwind CSS',
        expanded: `## Tech Stack\n- Framework: Next.js 16 (App Router)\n- Language: TypeScript strict mode\n- Styling: Tailwind CSS v4`,
      },
      {
        id: 'l2',
        label: 'Use pnpm, not npm',
        expanded: `## Package Manager\nAlways use pnpm. Never use npm or yarn — they will create conflicting lock files.`,
      },
      {
        id: 'l3',
        label: 'Never modify generated files in /prisma',
        expanded: `## Off-limits Files\n- /prisma/generated/ — auto-generated, never edit\n- /src/lib/gql/ — generated by graphql-codegen`,
      },
      {
        id: 'l4',
        label: 'Run `npm test` before committing',
        expanded: `## Before Committing\n1. Run \`npm test\` and ensure all tests pass\n2. Run \`npm run lint\` — fix all errors (warnings OK)`,
      },
    ],
  },
  {
    header: 'Coding Conventions',
    notes: [
      {
        id: 'l5',
        label: 'Prefer named exports over default exports',
        expanded: `## Code Style\n- Named exports only (no \`export default\` in components)\n- Use \`cn()\` from @/lib/utils for conditional classes`,
      },
      {
        id: 'l6',
        label: 'Error messages must be user-friendly',
        expanded: `## UX Rules\n- Never show raw error messages to users\n- Always provide actionable suggestions in error states`,
      },
      {
        id: 'l7',
        label: 'All API routes need rate limiting',
        expanded: `## Security\n- Every /api route must use the rate limiter from @/lib/rateLimit\n- Validate all inputs with Zod schemas`,
      },
      {
        id: 'l8',
        label: 'Components go in src/components/<feature>/',
        expanded: `## File Structure\n- Components: \`src/components/<feature>/ComponentName.tsx\`\n- Hooks: \`src/hooks/useFeatureName.ts\``,
      },
    ],
  },
];

const rightGroups: StickyGroup[] = [
  {
    header: 'Code Tasks (`/review`, `/test`)',
    notes: [
      {
        id: 'r1',
        label: '`/review` — Security + performance audit',
        expanded: `---\ndescription: Security and performance code review\nallowed-tools: [Read, Grep, Glob]\n---\n\nReview $ARGUMENTS for security vulnerabilities and performance issues.\n\nCheck for: SQL injection, XSS, N+1 queries, missing auth, unhandled errors.`,
      },
      {
        id: 'r2',
        label: '`/test` — Generate test file for current module',
        expanded: `---\ndescription: Generate tests for the current file\n---\n\nWrite comprehensive tests for $ARGUMENTS.\n\nUse the project test framework (Vitest). Cover happy paths, edge cases, and error states. Do not modify the source file.`,
      },
      {
        id: 'r3',
        label: '`/fix-types` — Resolve all TypeScript errors',
        expanded: `---\ndescription: Fix TypeScript errors in current file\n---\n\nRun \`npx tsc --noEmit\`, read the errors, then fix them one by one in $ARGUMENTS. Explain each fix briefly.`,
      },
    ],
  },
  {
    header: 'Workflow Tasks (`/commit`, `/deploy`)',
    notes: [
      {
        id: 'r4',
        label: '`/commit` — Stage, write message, push',
        expanded: `---\ndescription: Stage changes and create a conventional commit\n---\n\nRun \`git diff --staged\`, analyze the changes, write a conventional commit message (feat/fix/chore/docs), then commit with that message.`,
      },
      {
        id: 'r5',
        label: '`/deploy` — Run checks then `vercel --prod`',
        expanded: `---\ndescription: Run checks and deploy to production\n---\n\nRun \`npm run lint && npm test && npm audit --audit-level=high\` first. If all pass, run \`vercel --prod\`. Report the production URL when done.`,
      },
      {
        id: 'r6',
        label: '`/changelog` — Generate CHANGELOG from git log',
        expanded: `---\ndescription: Generate CHANGELOG from recent git history  \n---\n\nRun \`git log --oneline -30\`, group commits by type (feat/fix/chore), and write a markdown CHANGELOG section for the current version.`,
      },
    ],
  },
];

// ─── Sticky note component ────────────────────────────────────────────────────

interface StickyProps {
  note: StickyNote;
  colorClass: string;
  activeId: string | null;
  onToggle: (id: string) => void;
}

function Sticky({ note, colorClass, activeId, onToggle }: StickyProps) {
  const isActive = activeId === note.id;

  // Render label with backtick spans
  const labelParts = note.label.split(/(`[^`]+`)/g);

  return (
    <div className="flex flex-col">
      <button
        onClick={() => onToggle(note.id)}
        className={cn(
          'rounded-lg p-3 text-xs font-medium cursor-pointer select-none transition-all hover:scale-105 shadow-sm text-left',
          colorClass,
          isActive && 'ring-2 ring-primary scale-105',
        )}
      >
        {labelParts.map((part, i) =>
          part.startsWith('`') && part.endsWith('`') ? (
            <code
              key={i}
              className="px-1 rounded bg-black/10 dark:bg-white/10 font-mono"
            >
              {part.slice(1, -1)}
            </code>
          ) : (
            <span key={i}>{part}</span>
          )
        )}
      </button>

      <AnimatePresence>
        {isActive && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95, height: 0 }}
            animate={{ opacity: 1, scale: 1, height: 'auto' }}
            exit={{ opacity: 0, scale: 0.95, height: 0 }}
            transition={{ duration: 0.18, ease: 'easeOut' }}
            className="overflow-hidden"
          >
            <pre className="bg-muted rounded-lg p-3 font-mono text-xs mt-2 whitespace-pre text-left overflow-x-auto leading-5">
              {note.expanded}
            </pre>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// ─── Panel component ──────────────────────────────────────────────────────────

interface PanelProps {
  groups: StickyGroup[];
  stickyColorClass: string;
  activeId: string | null;
  onToggle: (id: string) => void;
}

function Panel({ groups, stickyColorClass, activeId, onToggle }: PanelProps) {
  return (
    <div className="space-y-6">
      {groups.map((group) => (
        <div key={group.header}>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">
            {group.header}
          </p>
          <div className="space-y-2">
            {group.notes.map((note) => (
              <Sticky
                key={note.id}
                note={note}
                colorClass={stickyColorClass}
                activeId={activeId}
                onToggle={onToggle}
              />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

export default function ContextVsSkillsVisual() {
  const [activeId, setActiveId] = useState<string | null>(null);

  const handleToggle = (id: string) => {
    setActiveId((prev) => (prev === id ? null : id));
  };

  return (
    <div className="w-full space-y-4">
      {/* Column headers */}
      <div className="grid grid-cols-1 md:grid-cols-[1fr_auto_1fr] gap-4">
        <div className="rounded-lg bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800/40 px-4 py-2 text-center">
          <span className="text-sm font-semibold text-yellow-800 dark:text-yellow-300">
            📄 Context — what Claude knows
          </span>
        </div>
        <div className="hidden md:flex items-center justify-center w-10" />
        <div className="rounded-lg bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800/40 px-4 py-2 text-center">
          <span className="text-sm font-semibold text-green-800 dark:text-green-300">
            ⚡ Skills — what Claude does
          </span>
        </div>
      </div>

      {/* Main two-panel grid */}
      <div className="grid grid-cols-1 md:grid-cols-[1fr_auto_1fr] gap-4 items-start">
        {/* Left panel — Context */}
        <div className="rounded-2xl border border-border bg-card p-6">
          <p className="text-sm font-bold text-foreground mb-4">
            CLAUDE.md
          </p>
          <Panel
            groups={leftGroups}
            stickyColorClass="bg-yellow-100 dark:bg-yellow-900/30 text-yellow-900 dark:text-yellow-200 hover:bg-yellow-200 dark:hover:bg-yellow-900/50"
            activeId={activeId}
            onToggle={handleToggle}
          />
        </div>

        {/* Divider */}
        <div className="hidden md:flex items-center justify-center self-stretch">
          <span className="text-4xl font-bold text-muted-foreground/30 select-none">
            +
          </span>
        </div>

        {/* Right panel — Skills */}
        <div className="rounded-2xl border border-border bg-card p-6">
          <p className="text-sm font-bold text-foreground mb-4">
            .claude/commands/
          </p>
          <Panel
            groups={rightGroups}
            stickyColorClass="bg-green-100 dark:bg-green-900/30 text-green-900 dark:text-green-200 hover:bg-green-200 dark:hover:bg-green-900/50"
            activeId={activeId}
            onToggle={handleToggle}
          />
        </div>
      </div>

      {/* Bottom caption */}
      <p className="text-center text-xs text-muted-foreground italic">
        Context persists across every conversation. Skills are invoked on demand.
      </p>
    </div>
  );
}
